package com.dovepay.jeemgr.dao.model;

public class TJeemgrSysRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE_MENU.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String onlineSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE_MENU.ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE_MENU.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE_MENU.ID
     *
     * @param id the value for T_JEEMGR_SYS_ROLE_MENU.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null || id.equals("") ? null : id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE_MENU.ROLE_ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE_MENU.ROLE_ID
     *
     * @param roleId the value for T_JEEMGR_SYS_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null || roleId.equals("") ? null : roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE_MENU.MENU_ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE_MENU.MENU_ID
     *
     * @param menuId the value for T_JEEMGR_SYS_ROLE_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null || menuId.equals("") ? null : menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE_MENU.ONLINE_SIGN
     *
     * @return the value of T_JEEMGR_SYS_ROLE_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getOnlineSign() {
        return onlineSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE_MENU.ONLINE_SIGN
     *
     * @param onlineSign the value for T_JEEMGR_SYS_ROLE_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setOnlineSign(String onlineSign) {
        this.onlineSign = onlineSign == null || onlineSign.equals("") ? null : onlineSign;
    }
}