package com.dovepay.jeemgr.dao.model;

public class TJeemgrSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER_ROLE.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER_ROLE.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String onlineSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER_ROLE.ID
     *
     * @return the value of T_JEEMGR_SYS_USER_ROLE.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER_ROLE.ID
     *
     * @param id the value for T_JEEMGR_SYS_USER_ROLE.ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null || id.equals("") ? null : id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER_ROLE.USER_ID
     *
     * @return the value of T_JEEMGR_SYS_USER_ROLE.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER_ROLE.USER_ID
     *
     * @param userId the value for T_JEEMGR_SYS_USER_ROLE.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null || userId.equals("") ? null : userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER_ROLE.ROLE_ID
     *
     * @return the value of T_JEEMGR_SYS_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for T_JEEMGR_SYS_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null || roleId.equals("") ? null : roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER_ROLE.ONLINE_SIGN
     *
     * @return the value of T_JEEMGR_SYS_USER_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getOnlineSign() {
        return onlineSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER_ROLE.ONLINE_SIGN
     *
     * @param onlineSign the value for T_JEEMGR_SYS_USER_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setOnlineSign(String onlineSign) {
        this.onlineSign = onlineSign == null || onlineSign.equals("") ? null : onlineSign;
    }
}