package com.dovepay.jeemgr.dao.model;

import java.util.Date;
import java.util.List;

public class TJeemgrSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.USERNAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.EMAIL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.MOBILE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.STATUS
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.CREATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_USER.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String onlineSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.USER_ID
     *
     * @return the value of T_JEEMGR_SYS_USER.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.USER_ID
     *
     * @param userId the value for T_JEEMGR_SYS_USER.USER_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null || userId.equals("") ? null : userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.USERNAME
     *
     * @return the value of T_JEEMGR_SYS_USER.USERNAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.USERNAME
     *
     * @param username the value for T_JEEMGR_SYS_USER.USERNAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null || username.equals("") ? null : username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.PASSWORD
     *
     * @return the value of T_JEEMGR_SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.PASSWORD
     *
     * @param password the value for T_JEEMGR_SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null || password.equals("") ? null : password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.EMAIL
     *
     * @return the value of T_JEEMGR_SYS_USER.EMAIL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.EMAIL
     *
     * @param email the value for T_JEEMGR_SYS_USER.EMAIL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null || email.equals("") ? null : email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.MOBILE
     *
     * @return the value of T_JEEMGR_SYS_USER.MOBILE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.MOBILE
     *
     * @param mobile the value for T_JEEMGR_SYS_USER.MOBILE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null || mobile.equals("") ? null : mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.STATUS
     *
     * @return the value of T_JEEMGR_SYS_USER.STATUS
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.STATUS
     *
     * @param status the value for T_JEEMGR_SYS_USER.STATUS
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.CREATE_TIME
     *
     * @return the value of T_JEEMGR_SYS_USER.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.CREATE_TIME
     *
     * @param createTime the value for T_JEEMGR_SYS_USER.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.CREATE_ID
     *
     * @return the value of T_JEEMGR_SYS_USER.CREATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.CREATE_ID
     *
     * @param createId the value for T_JEEMGR_SYS_USER.CREATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null || createId.equals("") ? null : createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.UPDATE_TIME
     *
     * @return the value of T_JEEMGR_SYS_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.UPDATE_TIME
     *
     * @param updateTime the value for T_JEEMGR_SYS_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.UPDATE_ID
     *
     * @return the value of T_JEEMGR_SYS_USER.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.UPDATE_ID
     *
     * @param updateId the value for T_JEEMGR_SYS_USER.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null || updateId.equals("") ? null : updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_USER.ONLINE_SIGN
     *
     * @return the value of T_JEEMGR_SYS_USER.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getOnlineSign() {
        return onlineSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_USER.ONLINE_SIGN
     *
     * @param onlineSign the value for T_JEEMGR_SYS_USER.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setOnlineSign(String onlineSign) {
        this.onlineSign = onlineSign == null || onlineSign.equals("") ? null : onlineSign;
    }
    
    private List<String> roleIdList;

	public List<String> getRoleIdList() {
		return roleIdList;
	}

	public void setRoleIdList(List<String> roleIdList) {
		this.roleIdList = roleIdList;
	}

}