package com.dovepay.jeemgr.dao.model;

public class TJeemgrSysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.URL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.TYPE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.ICON
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.LEVEL_NO
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Integer levelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.LEVEL_SEQ
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Integer levelSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String onlineSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.MENU_ID
     *
     * @return the value of T_JEEMGR_SYS_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.MENU_ID
     *
     * @param menuId the value for T_JEEMGR_SYS_MENU.MENU_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null || menuId.equals("") ? null : menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.PARENT_ID
     *
     * @return the value of T_JEEMGR_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.PARENT_ID
     *
     * @param parentId the value for T_JEEMGR_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null || parentId.equals("") ? null : parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.NAME
     *
     * @return the value of T_JEEMGR_SYS_MENU.NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.NAME
     *
     * @param name the value for T_JEEMGR_SYS_MENU.NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null || name.equals("") ? null : name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.URL
     *
     * @return the value of T_JEEMGR_SYS_MENU.URL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.URL
     *
     * @param url the value for T_JEEMGR_SYS_MENU.URL
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null || url.equals("") ? null : url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.TYPE
     *
     * @return the value of T_JEEMGR_SYS_MENU.TYPE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.TYPE
     *
     * @param type the value for T_JEEMGR_SYS_MENU.TYPE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setType(String type) {
        this.type = type == null || type.equals("") ? null : type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.ICON
     *
     * @return the value of T_JEEMGR_SYS_MENU.ICON
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.ICON
     *
     * @param icon the value for T_JEEMGR_SYS_MENU.ICON
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null || icon.equals("") ? null : icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.LEVEL_NO
     *
     * @return the value of T_JEEMGR_SYS_MENU.LEVEL_NO
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Integer getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.LEVEL_NO
     *
     * @param levelNo the value for T_JEEMGR_SYS_MENU.LEVEL_NO
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setLevelNo(Integer levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.LEVEL_SEQ
     *
     * @return the value of T_JEEMGR_SYS_MENU.LEVEL_SEQ
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Integer getLevelSeq() {
        return levelSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.LEVEL_SEQ
     *
     * @param levelSeq the value for T_JEEMGR_SYS_MENU.LEVEL_SEQ
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setLevelSeq(Integer levelSeq) {
        this.levelSeq = levelSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_MENU.ONLINE_SIGN
     *
     * @return the value of T_JEEMGR_SYS_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getOnlineSign() {
        return onlineSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_MENU.ONLINE_SIGN
     *
     * @param onlineSign the value for T_JEEMGR_SYS_MENU.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setOnlineSign(String onlineSign) {
        this.onlineSign = onlineSign == null || onlineSign.equals("") ? null : onlineSign;
    }
}