package com.dovepay.jeemgr.dao.model;

import java.util.Date;
import java.util.List;

public class TJeemgrSysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.CREAT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String creatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JEEMGR_SYS_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    private String onlineSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.ROLE_ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for T_JEEMGR_SYS_ROLE.ROLE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null || roleId.equals("") ? null : roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.ROLE_NAME
     *
     * @return the value of T_JEEMGR_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_JEEMGR_SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null || roleName.equals("") ? null : roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.CREAT_ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE.CREAT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.CREAT_ID
     *
     * @param creatId the value for T_JEEMGR_SYS_ROLE.CREAT_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setCreatId(String creatId) {
        this.creatId = creatId == null || creatId.equals("") ? null : creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.CREATE_TIME
     *
     * @return the value of T_JEEMGR_SYS_ROLE.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.CREATE_TIME
     *
     * @param createTime the value for T_JEEMGR_SYS_ROLE.CREATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.UPDATE_ID
     *
     * @return the value of T_JEEMGR_SYS_ROLE.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.UPDATE_ID
     *
     * @param updateId the value for T_JEEMGR_SYS_ROLE.UPDATE_ID
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null || updateId.equals("") ? null : updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.UPDATE_TIME
     *
     * @return the value of T_JEEMGR_SYS_ROLE.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.UPDATE_TIME
     *
     * @param updateTime the value for T_JEEMGR_SYS_ROLE.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JEEMGR_SYS_ROLE.ONLINE_SIGN
     *
     * @return the value of T_JEEMGR_SYS_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public String getOnlineSign() {
        return onlineSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JEEMGR_SYS_ROLE.ONLINE_SIGN
     *
     * @param onlineSign the value for T_JEEMGR_SYS_ROLE.ONLINE_SIGN
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    public void setOnlineSign(String onlineSign) {
        this.onlineSign = onlineSign == null || onlineSign.equals("") ? null : onlineSign;
    }
    
    
    private List<String> functionIdList;
    /**
	 * @return the functionIdList
	 */
	public List<String> getFunctionIdList() {
		return functionIdList;
	}

	/**
	 * @param functionIdList
	 *            the functionIdList to set
	 */
	public void setFunctionIdList(List<String> functionIdList) {
		this.functionIdList = functionIdList;
	}
}