package com.dovepay.jeemgr.dao.mapper;

import com.dovepay.jeemgr.dao.model.TJeemgrSysUserRole;
import com.dovepay.jeemgr.dao.model.TJeemgrSysUserRoleExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TJeemgrSysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int countByExample(TJeemgrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByExample(TJeemgrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insert(TJeemgrSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insertSelective(TJeemgrSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    List<TJeemgrSysUserRole> selectByExample(TJeemgrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    TJeemgrSysUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") TJeemgrSysUserRole record, @Param("example") TJeemgrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExample(@Param("record") TJeemgrSysUserRole record, @Param("example") TJeemgrSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKeySelective(TJeemgrSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKey(TJeemgrSysUserRole record);

	void deleteByRoleIdAndType(@Param("roleId") String roleId,@Param("ONLINE_SIGN") String ONLINE_SIGN);

	void deleteUserRoleByUserName(@Param("userName") String userName,@Param("ONLINE_SIGN") String ONLINE_SIGN);
}