package com.dovepay.jeemgr.dao.mapper;

import com.dovepay.jeemgr.dao.model.TJeemgrSysUser;
import com.dovepay.jeemgr.dao.model.TJeemgrSysUserExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

public interface TJeemgrSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int countByExample(TJeemgrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByExample(TJeemgrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insert(TJeemgrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insertSelective(TJeemgrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    List<TJeemgrSysUser> selectByExample(TJeemgrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    TJeemgrSysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") TJeemgrSysUser record, @Param("example") TJeemgrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExample(@Param("record") TJeemgrSysUser record, @Param("example") TJeemgrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKeySelective(TJeemgrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_USER
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKey(TJeemgrSysUser record);

	List<TJeemgrSysUser> selectAllInfoByPage(@Param("paraMap") Map<String, Object> paraMap);

	void deleteUserByIdAndType(@Param("username") String username,@Param("ONLINE_SIGN") String ONLINE_SIGN);
}