package com.dovepay.jeemgr.dao.mapper;

import com.dovepay.jeemgr.dao.model.TJeemgrSysRole;
import com.dovepay.jeemgr.dao.model.TJeemgrSysRoleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TJeemgrSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int countByExample(TJeemgrSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByExample(TJeemgrSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insert(TJeemgrSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int insertSelective(TJeemgrSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    List<TJeemgrSysRole> selectByExample(TJeemgrSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    TJeemgrSysRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") TJeemgrSysRole record, @Param("example") TJeemgrSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByExample(@Param("record") TJeemgrSysRole record, @Param("example") TJeemgrSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKeySelective(TJeemgrSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JEEMGR_SYS_ROLE
     *
     * @mbggenerated Tue Nov 20 16:55:39 CST 2018
     */
    int updateByPrimaryKey(TJeemgrSysRole record);
    
    List<TJeemgrSysRole> selectRoleInPage(@Param("paraMap") Map<String, Object> paraMap);
    
	List<TJeemgrSysRole> selectRoleListByUserId(@Param("params") Map<String, Object> map);

	void deleteByIdAndType(@Param("roleId") String roleId, @Param("ONLINE_SIGN") String ONLINE_SIGN);

}